name: agentivity_sdk_flutter

command:
  version:
    linkToCommits: true
    workspaceChangelog: true
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- "dart analyze --fatal-warnings"
    description: Analyze every package in the workspace.

  test:
    run: melos exec --dir-exists=test -- "dart test"
    description: Run tests for every package that has a test/ directory.
