name: agentivity_sdk_flutter_workspace
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  melos: ^8.6.0

workspace:
  - packages/agentivity_ag_ui
  - packages/agentivity_artifacts
  - packages/agentivity_client
