import 'package:agentivity_artifacts/agentivity_artifacts.dart';
import 'package:flutter/material.dart';

import '_demo_common.dart';

class DemoAgentLog extends StatelessWidget {
  const DemoAgentLog({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamingDemoPage(
      title: 'Agent Activity Log',
      sections: [
        DemoSection(
          label: 'Run Summary',
          delayMs: 350,
          child: AgStatGrid(props: {
            'columns': 4,
            'metrics': [
              {'title': 'Tokens',    'value': '4,218',  'delta': '+22 %',  'trend': 'up',   'subtitle': 'vs last run'},
              {'title': 'Duration',  'value': '8.3 s',  'delta': '−1.1 s', 'trend': 'down', 'subtitle': 'improved'},
              {'title': 'Steps',     'value': '7',       'delta': 'flat',   'trend': 'flat', 'subtitle': 'tool calls: 3'},
              {'title': 'Est. Cost', 'value': '\$0.12',  'delta': 'flat',   'trend': 'flat', 'subtitle': 'claude-opus'},
            ],
          }),
        ),
        DemoSection(
          label: 'Status',
          delayMs: 750,
          child: Column(
            children: [
              AgStatusCard(props: {
                'title': 'Task completed',
                'status': 'success',
                'message': 'All 3 source files retrieved and analysed.',
                'details': [
                  '14,218 tokens indexed across 3 files',
                  'Avg. relevance score: 0.87',
                  'No conflicting instructions detected',
                ],
              }),
              const SizedBox(height: 8),
              AgStatusCard(props: {
                'title': 'Context limit warning',
                'status': 'warning',
                'message': '72 % of context window consumed.',
                'details': [
                  '4,892 tokens remaining',
                  'Consider enabling summarisation',
                ],
              }),
            ],
          ),
        ),
        DemoSection(
          label: 'Execution Timeline',
          delayMs: 900,
          child: AgTimeline(props: {
            'title': 'Agent run · session sess_01HX9K',
            'events': [
              {'label': 'Reasoning',               'time': '0.0 s', 'status': 'success', 'note': 'Parsed user intent — code generation task'},
              {'label': 'tool_call: search_web',   'time': '0.4 s', 'status': 'success', 'note': '"Flutter fl_chart examples" → 12 results'},
              {'label': 'tool_call: read_file',    'time': '1.9 s', 'status': 'success', 'note': 'main.dart  (847 tokens)'},
              {'label': 'tool_call: read_file',    'time': '2.3 s', 'status': 'success', 'note': 'pubspec.yaml  (128 tokens)'},
              {'label': 'Reasoning',               'time': '2.8 s', 'status': 'success', 'note': 'Evaluating context — selecting widget pattern'},
              {'label': 'tool_call: write_file',   'time': '4.1 s', 'status': 'running', 'note': 'Streaming generated artifact widget…'},
              {'label': 'Response',                'time': '',       'status': 'pending'},
            ],
          }),
        ),
        DemoSection(
          label: 'Tool Call Payload',
          delayMs: 850,
          child: AgJsonViewer(props: {
            'title': 'write_file · call_8f3a9b',
            'data': {
              'tool': 'write_file',
              'call_id': 'call_8f3a9b',
              'args': {
                'path': 'lib/widgets/revenue_chart.dart',
                'overwrite': true,
                'content': '// Generated by agent',
              },
              'context': {
                'session_id': 'sess_01HX9K',
                'model': 'claude-opus-4-5',
                'step': 6,
                'input_tokens': 3847,
                'output_tokens': 371,
              },
            },
            'expanded': true,
          }),
        ),
        DemoSection(
          label: 'Generated Code',
          delayMs: 900,
          child: AgCodeBlock(props: {
            'title': 'revenue_chart.dart  · output of write_file',
            'language': 'dart',
            'code': r"""import 'package:agentivity_artifacts/agentivity_artifacts.dart';
import 'package:flutter/material.dart';

/// Revenue bar chart — generated by the AI agent.
class AgentRevenueChart extends StatelessWidget {
  const AgentRevenueChart({super.key, required this.weeks});

  final List<double> weeks;

  @override
  Widget build(BuildContext context) {
    return AgBarChart(
      props: {
        'title': 'Weekly Revenue (k€)',
        'labels': List.generate(weeks.length, (i) => 'W${i + 1}'),
        'datasets': [{'label': 'Revenue', 'data': weeks}],
        'height': 200,
      },
    );
  }
}""",
            'maxLines': 22,
          }),
        ),
      ],
    );
  }
}
